#
# JBZoo Toolbox - PHPUnit
#
# This file is part of the JBZoo Toolbox project.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @package    PHPUnit
# @license    MIT
# @copyright  Copyright (C) JBZoo.com, All rights reserved.
# @link       https://github.com/JBZoo/PHPUnit
#

language: php
os: linux
dist: xenial

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0

matrix:
  fast_finish: true
  allow_failures:
    - php: 8.0

env:
  matrix:
    - JBZOO_COMPOSER_UPDATE_FLAGS="--prefer-lowest --prefer-stable"
    - JBZOO_COMPOSER_UPDATE_FLAGS=""
    - XDEBUG_OFF="yes"

before_script:
  - composer self-update
  - if [[ $XDEBUG_OFF = yes ]]; then phpenv config-rm xdebug.ini; fi;
  - echo 'xdebug.mode=coverage' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
  - make update        --no-print-directory
  - make server-start  --no-print-directory
  - make test-all      --no-print-directory

after_script:
  - make report-coveralls
